# General  
finetune: True
partial_train: null

# Traning 
epochs: 600
batch_size: 4
lr_backbone: 0.0001
lr_head: 0.001
weight_decay: 0.01
lr_decay: 0.99
ccl: 0.5
scl: 0.5

#    batch_size |   ccl |   depth | head_version   |   hidden_dim |   lr_backbone |     lr_head |   scl
# Model       4 |  2    |       5 | series         |         1024 |   0.000600529 | 0.00488126  |  2 
backbone: DSTformerv2
model_version: class
maxlen: 243
dim_feat: 512 # org 512, ours 256
mlp_ratio: 2 # org 2, ours 4
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.5
head_version: base

# Data
dataset: ntu60_hrnet #ntu60_all  #ntu60_hrnet #ntu60_openpifpaf_HQ_fixed4 #ntu60_openpifpaf_HQ
data_split: xsub
clip_len: 243
action_classes: 60

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]